# .travis.yml

language: python
python: 3.6
sudo: required

env: # Link to LaTeX directory (must match .nmc.profile).
  - PATH: /usr/local/texlive/foam/bin/x86_64-linux:$PATH

before_install:
  - python travis_pre.py

install: # Download and install a vanilla TexLive.
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzf install-tl-unx.tar.gz
  - cd install-tl-*
  - sudo ./install-tl -profile=../.nmc.profile
  - cd ../

script: # Compile the major tex files.
  - ./compile_labs.sh

deploy: # Deploy the major pdf files to releases when tagged.
  provider: releases
  api_key:
    secure: YQBe6vASTDL6qPjFYBptLL6F7dUntTngOQc6+vN34uhP5+rqwxE7JdswHuynDJjujsivCkA71oL1Xy17O9UAXaePYkN/SUfkwdZCOtgRFxIWiwJMqCAKeMvE9C99uI4x4OcS0g3/S2FKc2OAPVS5arp67RBheKa5i1LxaVVhNHz7uf3H7d+4ZUZkxDDQL0VgxbGeBpAvC+Qw6EmNcl1AEqTrBq/upAukPX5/onurXb58/MQfChAwru5pI9dvsMsnyIWfrQekop51FAzyTybuSWlBE2yqanS2+51/vzmrauqWlQO+4+RaKeN8M5i6o982A7Xgyt54H7d5xzi4xzv+sovLc1jguUcAtO0quQZQzy20UlaT5tM10OHWxeuxCTWeOQrEh7nemsfT9UYAAXlXwQekYJ3GuBSpnGUrFBHPeJf8XGVyRU1+SJqsbhBGNR1EQbCWpY04lfeyj9Zmx33xei45LQx6pDtszslTR5R04jse+uIX7t84jHFZwALR6PwuWBCbkoOhgeTdMNGQGAgQwOd35aStZ4lDLzzrk+ORgAaWxsZqUs9UsF2U0tl3UtLMgJ+IjtPXhTRq/eNGT9+Kr2yY2gpTe4ESERQuuwk1ZzvTOaUYvsCNbOTaS2OU4DeyA5diZvDmhGpuAKWaJk5D1DBrt4T90gpQNVxkr+RGkrM=
  file:
    - "docs/GettingStarted.pdf"
    - "docs/PythonEssentials.pdf"
    - "docs/DataScienceEssentials.pdf"
    - "docs/Volume1.pdf"
    - "docs/Volume2.pdf"
    - "docs/Volume3.pdf"
    - "docs/Volume4.pdf"
  skip_cleanup: true
  on:
    tags: true
